### ISSUE TITLE
WebSocket needs Zero

### ISSUE THREAD

**Issue by robrons96** [NilsG-S/antifreeze-back-end#26]
* The WebSocket connection does not post the integer value 0 as temperature to the device. 
* The error received is as follows:
```
{"message":"Invald input: Key: 'TempInput.Temp' Error:Field validation for 'Temp' failed on the 'required' tag"}
```
* I suspect a check for values like 01, 002 etc. might be causing this issue.

**Comment by NilsG-S** [comment]
https://stackoverflow.com/questions/38486564/golang-unmarshal-marshal-json-with-int-set-to-0-does-not-seem-to-work

Basically I need to switch to using pointers when an integer may be zero

**Comment by NilsG-S** [comment]
Fixed on temp-fix
